export const employees = [
  {
    firstName: "Jean",
    lastName: "Dupont",
    dateOfBirth: "12/05/1990",
    startDate: "01/07/2023",
    department: "Sales",
    street: "123 Main Street",
    city: "New York",
    state: "NY",
    zipCode: "10001",
  },
  {
    firstName: "Alice",
    lastName: "Martin",
    dateOfBirth: "22/09/1985",
    startDate: "15/06/2022",
    department: "Marketing",
    street: "456 Elm Avenue",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
  },
  {
    firstName: "Thomas",
    lastName: "Smith",
    dateOfBirth: "05/03/1995",
    startDate: "02/01/2023",
    department: "Engineering",
    street: "789 Oak Road",
    city: "San Francisco",
    state: "CA",
    zipCode: "94101",
  },
  {
    firstName: "Sophie",
    lastName: "Johnson",
    dateOfBirth: "18/07/1988",
    startDate: "10/03/2024",
    department: "Human Resources",
    street: "101 Pine Lane",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
  },
  {
    firstName: "Lucas",
    lastName: "Williams",
    dateOfBirth: "30/11/1992",
    startDate: "05/09/2023",
    department: "Legal",
    street: "222 Cedar Street",
    city: "Houston",
    state: "TX",
    zipCode: "77002",
  },
  {
    firstName: "Emily",
    lastName: "Anderson",
    dateOfBirth: "14/03/1987",
    startDate: "20/10/2023",
    department: "Engineering",
    street: "789 Elm Street",
    city: "Austin",
    state: "TX",
    zipCode: "78701",
  },
  {
    firstName: "Michael",
    lastName: "Garcia",
    dateOfBirth: "03/09/1993",
    startDate: "05/02/2022",
    department: "Sales",
    street: "456 Oak Avenue",
    city: "Miami",
    state: "FL",
    zipCode: "33101",
  },
  {
    firstName: "Emma",
    lastName: "Brown",
    dateOfBirth: "27/06/1996",
    startDate: "15/11/2023",
    department: "Legal",
    street: "101 Maple Road",
    city: "Boston",
    state: "MA",
    zipCode: "02101",
  },
];
