export const employees = [
  {
    firstName: "Sarah",
    lastName: "Martinez",
    dateOfBirth: "05-11-1987",
    startDate: "01-20-2018",
    department: "Marketing",
    street: "456 Oak Street",
    city: "San Francisco",
    state: "California",
    zipCode: "94103",
  },
  {
    firstName: "Rajesh",
    lastName: "Kumar",
    dateOfBirth: "10-02-1975",
    startDate: "07-15-2014",
    department: "Engineering",
    street: "789 Pine Road",
    city: "Seattle",
    state: "Washington",
    zipCode: "98101",
  },
  {
    firstName: "Emily",
    lastName: "Clark",
    dateOfBirth: "03-29-1990",
    startDate: "11-05-2016",
    department: "Human Resources",
    street: "321 Birch Ave",
    city: "New York",
    state: "New York",
    zipCode: "10001",
  },
  {
    firstName: "David",
    lastName: "Wang",
    dateOfBirth: "12-14-1982",
    startDate: "05-22-2017",
    department: "Legal",
    street: "654 Cedar Blvd",
    city: "Los Angeles",
    state: "California",
    zipCode: "90001",
  },
  {
    firstName: "Linda",
    lastName: "Brown",
    dateOfBirth: "07-08-1978",
    startDate: "02-09-2013",
    department: "Sales",
    street: "987 Elm Street",
    city: "Austin",
    state: "Texas",
    zipCode: "73301",
  },
  {
    firstName: "Andre",
    lastName: "Giroux",
    dateOfBirth: "04-16-1984",
    startDate: "08-03-2019",
    department: "Finance",
    street: "102 Willow Lane",
    city: "Miami",
    state: "Florida",
    zipCode: "33101",
  },
  {
    firstName: "Zara",
    lastName: "Ali",
    dateOfBirth: "09-30-1992",
    startDate: "06-10-2020",
    department: "Marketing",
    street: "208 Birch Road",
    city: "Houston",
    state: "Texas",
    zipCode: "77001",
  },
  {
    firstName: "Jason",
    lastName: "Kim",
    dateOfBirth: "01-05-1988",
    startDate: "12-17-2016",
    department: "Engineering",
    street: "305 Cedar Street",
    city: "Denver",
    state: "Colorado",
    zipCode: "80201",
  },
  {
    firstName: "Natalie",
    lastName: "Rivera",
    dateOfBirth: "06-22-1991",
    startDate: "04-25-2018",
    department: "Human Resources",
    street: "419 Maple Ave",
    city: "Boston",
    state: "Massachusetts",
    zipCode: "02101",
  },
  {
    firstName: "Julia",
    lastName: "Thompson",
    dateOfBirth: "08-13-1986",
    startDate: "09-29-2017",
    department: "Sales",
    street: "602 Pine Lane",
    city: "Las Vegas",
    state: "Nevada",
    zipCode: "89101",
  },
  {
    firstName: "Carlos",
    lastName: "Gonzalez",
    dateOfBirth: "12-24-1983",
    startDate: "05-14-2014",
    department: "Finance",
    street: "731 Elm Street",
    city: "San Diego",
    state: "California",
    zipCode: "92101",
  },
  {
    firstName: "Sofia",
    lastName: "Martini",
    dateOfBirth: "03-02-1995",
    startDate: "10-21-2019",
    department: "Marketing",
    street: "864 Birch Road",
    city: "Phoenix",
    state: "Arizona",
    zipCode: "85001",
  },
  {
    firstName: "Liam",
    lastName: "O'Brien",
    dateOfBirth: "02-15-1990",
    startDate: "07-07-2018",
    department: "Engineering",
    street: "915 Cedar Ave",
    city: "San Jose",
    state: "California",
    zipCode: "95101",
  },
  {
    firstName: "Aisha",
    lastName: "Khan",
    dateOfBirth: "10-08-1989",
    startDate: "01-03-2016",
    department: "Human Resources",
    street: "1001 Maple Street",
    city: "Indianapolis",
    state: "Indiana",
    zipCode: "46201",
  },
  {
    firstName: "Elena",
    lastName: "Vasquez",
    dateOfBirth: "07-17-1976",
    startDate: "03-22-2017",
    department: "Legal",
    street: "1209 Oak Lane",
    city: "Portland",
    state: "Oregon",
    zipCode: "97201",
  },
  {
    firstName: "Omar",
    lastName: "Farooq",
    dateOfBirth: "05-29-1985",
    startDate: "11-15-2020",
    department: "Sales",
    street: "1328 Pine Street",
    city: "Atlanta",
    state: "Georgia",
    zipCode: "30301",
  },
  {
    firstName: "Alice",
    lastName: "Wong",
    dateOfBirth: "02-23-1994",
    startDate: "06-28-2019",
    department: "Finance",
    street: "1456 Birch Road",
    city: "Dallas",
    state: "Texas",
    zipCode: "75201",
  },
  {
    firstName: "Benjamin",
    lastName: "Taylor",
    dateOfBirth: "08-04-1988",
    startDate: "04-16-2015",
    department: "Marketing",
    street: "1594 Cedar Ave",
    city: "Charlotte",
    state: "North Carolina",
    zipCode: "28201",
  },
  {
    firstName: "Priya",
    lastName: "Patel",
    dateOfBirth: "01-12-1992",
    startDate: "09-03-2018",
    department: "Engineering",
    street: "1730 Maple Blvd",
    city: "Columbus",
    state: "Ohio",
    zipCode: "43201",
  },
  {
    firstName: "Lucas",
    lastName: "Smith",
    dateOfBirth: "11-30-1974",
    startDate: "02-20-2016",
    department: "Human Resources",
    street: "1875 Oak Street",
    city: "Baltimore",
    state: "Maryland",
    zipCode: "21201",
  },
  {
    firstName: "Amina",
    lastName: "Mohammed",
    dateOfBirth: "04-07-1989",
    startDate: "08-11-2017",
    department: "Legal",
    street: "2019 Pine Lane",
    city: "Nashville",
    state: "Tennessee",
    zipCode: "37201",
  },
  {
    firstName: "Kyle",
    lastName: "Anderson",
    dateOfBirth: "09-15-1990",
    startDate: "12-05-2019",
    department: "Sales",
    street: "2153 Birch Road",
    city: "Milwaukee",
    state: "Wisconsin",
    zipCode: "53201",
  },
  {
    firstName: "Sophie",
    lastName: "Martin",
    dateOfBirth: "06-26-1978",
    startDate: "05-10-2014",
    department: "Finance",
    street: "2298 Cedar Street",
    city: "Memphis",
    state: "Tennessee",
    zipCode: "38101",
  },
  {
    firstName: "Hassan",
    lastName: "Kareem",
    dateOfBirth: "03-18-1987",
    startDate: "01-14-2020",
    department: "Marketing",
    street: "2441 Maple Ave",
    city: "New Orleans",
    state: "Louisiana",
    zipCode: "70112",
  },
];
